use_field_init_shorthand = true
newline_style            = "Unix"
style_edition            = "2024"
max_width                = 100
reorder_imports          = false
edition                  = "2024"
hard_tabs                = false
tab_spaces               = 4
use_small_heuristics     = "Default"
force_explicit_abi       = true
match_block_trailing_comma = false
remove_nested_parens     = true
use_try_shorthand        = true
