use_field_init_shorthand = true
newline_style = "Unix"
style_edition = "2024"
max_width = 100
wrap_comments = false
comment_width = 100
normalize_comments = true
reorder_imports = false
merge_imports = true
edition = "2024"
hard_tabs = false
tab_spaces = 4
imports_granularity = "Crate"
group_imports = "StdExternalCrate"
use_small_heuristics = "Default"
fn_single_line = false
where_single_line = false
force_explicit_abi = true
format_strings = false
format_macro_matchers = true
format_macro_bodies = true
match_arm_blocks = true
match_block_trailing_comma = false
overflow_delimited_expr = false
remove_nested_parens = true
reorder_impl_items = false
space_after_colon = true
space_before_colon = false
struct_lit_single_line = true
trailing_comma = "Vertical"
trailing_semicolon = true
type_punctuation_density = "Wide"
use_try_shorthand = true
version = "Two"
