#!/usr/bin/env python3
"""Generates the knot sample model: knot.obj, knot.mtl, diffuse.png.

A first-party replacement for the repository's earlier textured sample,
whose origin could not be established. Everything here is computed, so the
model carries no third-party terms: the mesh is a trefoil torus knot with
a parallel-transport tube frame, and the texture is a banded pattern with
deterministic speckles, loud enough that an untextured render is obvious
at a glance.

Deterministic by construction: fixed seed, fixed float formatting, no
dependencies outside the Python standard library. Regenerate with

    python3 res/models/knot/gen.py

and the three outputs are byte-identical on any platform.
"""

import math
import os
import struct
import zlib

SEGMENTS = 320  # rings along the knot
AROUND = 80  # vertices around the tube
TUBE_RADIUS = 0.42
SCALE = 0.55  # overall curve scale; the viewer auto-frames regardless
TEX_SIZE = 1024

OUT_DIR = os.path.dirname(os.path.abspath(__file__))


def curve(t: float) -> tuple[float, float, float]:
    """The trefoil knot curve, scaled."""
    x = math.sin(t) + 2.0 * math.sin(2.0 * t)
    y = math.cos(t) - 2.0 * math.cos(2.0 * t)
    z = -math.sin(3.0 * t)
    return (SCALE * x, SCALE * y, SCALE * z)


def sub(a, b):
    return (a[0] - b[0], a[1] - b[1], a[2] - b[2])


def add(a, b):
    return (a[0] + b[0], a[1] + b[1], a[2] + b[2])


def mul(a, s):
    return (a[0] * s, a[1] * s, a[2] * s)


def dot(a, b):
    return a[0] * b[0] + a[1] * b[1] + a[2] * b[2]


def cross(a, b):
    return (
        a[1] * b[2] - a[2] * b[1],
        a[2] * b[0] - a[0] * b[2],
        a[0] * b[1] - a[1] * b[0],
    )


def norm(a):
    length = math.sqrt(dot(a, a))
    return (a[0] / length, a[1] / length, a[2] / length)


def frames():
    """Tangents and a parallel-transport frame that closes exactly.

    Parallel transport avoids the flips a fixed reference vector produces
    on a curve like this, but after one full loop the frame comes back
    rotated by its holonomy angle. That angle is measured and unwound
    linearly along the curve, so ring 0 and ring SEGMENTS coincide and the
    tube is watertight at the seam.
    """
    ts = [2.0 * math.pi * i / SEGMENTS for i in range(SEGMENTS)]
    eps = 1.0e-4
    tangents = [norm(sub(curve(t + eps), curve(t - eps))) for t in ts]

    # Seed the frame with any vector not parallel to the first tangent.
    seed = (0.0, 0.0, 1.0)
    if abs(dot(seed, tangents[0])) > 0.9:
        seed = (1.0, 0.0, 0.0)
    n0 = norm(sub(seed, mul(tangents[0], dot(seed, tangents[0]))))
    normals = [n0]
    for i in range(1, SEGMENTS):
        prev = normals[-1]
        projected = sub(prev, mul(tangents[i], dot(prev, tangents[i])))
        normals.append(norm(projected))

    # Holonomy: transport once more onto tangent 0 and measure the angle
    # against where the frame started.
    wrapped = norm(sub(normals[-1], mul(tangents[0], dot(normals[-1], tangents[0]))))
    binorm0 = cross(tangents[0], n0)
    angle = math.atan2(dot(wrapped, binorm0), dot(wrapped, n0))

    out = []
    for i in range(SEGMENTS):
        correction = -angle * i / SEGMENTS
        c, s = math.cos(correction), math.sin(correction)
        binorm = cross(tangents[i], normals[i])
        n = add(mul(normals[i], c), mul(binorm, s))
        out.append((tangents[i], norm(n)))
    return ts, out


def write_obj() -> None:
    ts, frame = frames()
    positions = []
    normals = []
    # Rings 0..SEGMENTS-1 are computed; the seam ring reuses ring 0 by
    # index so the mesh is watertight by construction rather than within
    # floating-point error.
    for i in range(SEGMENTS):
        centre = curve(ts[i])
        tangent, n = frame[i]
        binorm = cross(tangent, n)
        for j in range(AROUND):
            phi = 2.0 * math.pi * j / AROUND
            c, s = math.cos(phi), math.sin(phi)
            radial = add(mul(n, c), mul(binorm, s))
            positions.append(add(centre, mul(radial, TUBE_RADIUS)))
            normals.append(radial)

    lines = [
        "# Generated by gen.py in this directory; do not edit by hand.",
        "# First-party sample model: a trefoil torus knot.",
        "mtllib knot.mtl",
        "o knot",
    ]
    for p in positions:
        lines.append(f"v {p[0]:.6f} {p[1]:.6f} {p[2]:.6f}")
    # Texcoords carry the seam explicitly: u runs 0..1 inclusive, v too.
    for i in range(SEGMENTS + 1):
        for j in range(AROUND + 1):
            lines.append(f"vt {i / SEGMENTS:.6f} {j / AROUND:.6f}")
    for n in normals:
        lines.append(f"vn {n[0]:.6f} {n[1]:.6f} {n[2]:.6f}")
    lines.append("usemtl knot")

    def vidx(i: int, j: int) -> int:
        return (i % SEGMENTS) * AROUND + (j % AROUND) + 1

    def tidx(i: int, j: int) -> int:
        return i * (AROUND + 1) + j + 1

    for i in range(SEGMENTS):
        for j in range(AROUND):
            a = (vidx(i, j), tidx(i, j))
            b = (vidx(i + 1, j), tidx(i + 1, j))
            c = (vidx(i + 1, j + 1), tidx(i + 1, j + 1))
            d = (vidx(i, j + 1), tidx(i, j + 1))
            lines.append(f"f {a[0]}/{a[1]}/{a[0]} {b[0]}/{b[1]}/{b[0]} {c[0]}/{c[1]}/{c[0]}")
            lines.append(f"f {a[0]}/{a[1]}/{a[0]} {c[0]}/{c[1]}/{c[0]} {d[0]}/{d[1]}/{d[0]}")

    with open(os.path.join(OUT_DIR, "knot.obj"), "w", newline="\n") as f:
        f.write("\n".join(lines) + "\n")


def write_mtl() -> None:
    text = "\n".join(
        [
            "# Generated by gen.py in this directory; do not edit by hand.",
            "newmtl knot",
            "Ka 1.000000 1.000000 1.000000",
            "Kd 1.000000 1.000000 1.000000",
            "Ks 0.120000 0.120000 0.120000",
            "Ns 32.000000",
            "map_Kd diffuse.png",
        ]
    )
    with open(os.path.join(OUT_DIR, "knot.mtl"), "w", newline="\n") as f:
        f.write(text + "\n")


class Lcg:
    """A tiny deterministic generator so the speckles never move."""

    def __init__(self, seed: int) -> None:
        self.state = seed & 0xFFFFFFFF

    def next(self) -> int:
        self.state = (self.state * 1664525 + 1013904223) & 0xFFFFFFFF
        return self.state

    def unit(self) -> float:
        return self.next() / 0xFFFFFFFF


PALETTE = [
    (31, 119, 148),  # deep teal
    (77, 208, 189),  # turquoise
    (250, 227, 158),  # cream
    (247, 148, 116),  # coral
    (198, 46, 101),  # magenta
    (52, 52, 56),  # near black
    (128, 128, 132),  # grey
    (208, 208, 210),  # light grey
]


def write_png() -> None:
    size = TEX_SIZE
    bands = 16  # bands along u so stretching is visible per knot winding
    rng = Lcg(0x534C5859)  # "SLXY"
    speckles = []
    for _ in range(220):
        speckles.append(
            (
                rng.unit() * size,
                rng.unit() * size,
                4.0 + rng.unit() * 14.0,
                rng.next() % 2,
            )
        )

    by_row: list[list[tuple[float, float, float, int]]] = [[] for _ in range(size)]
    for sx, sy, radius, dark in speckles:
        lo = max(0, int(sy - radius))
        hi = min(size - 1, int(sy + radius))
        for y in range(lo, hi + 1):
            by_row[y].append((sx, sy, radius, dark))

    rows = []
    for y in range(size):
        row = bytearray()
        row.append(0)  # filter type: none
        active = by_row[y]
        for x in range(size):
            band = (x * bands) // size
            r, g, b = PALETTE[band % len(PALETTE)]
            # A fine microgrid so texel density reads in close-ups.
            if x % 64 == 0 or y % 64 == 0:
                r = int(r * 0.72)
                g = int(g * 0.72)
                b = int(b * 0.72)
            for sx, sy, radius, dark in active:
                dx = x - sx
                dy = y - sy
                if dx * dx + dy * dy < radius * radius:
                    if dark:
                        r = int(r * 0.45)
                        g = int(g * 0.45)
                        b = int(b * 0.45)
                    else:
                        r = min(255, int(r * 1.35) + 40)
                        g = min(255, int(g * 1.35) + 40)
                        b = min(255, int(b * 1.35) + 40)
                    break
            row += bytes((r, g, b))
        rows.append(bytes(row))

    def chunk(ctype: bytes, body: bytes) -> bytes:
        return (
            struct.pack(">I", len(body))
            + ctype
            + body
            + struct.pack(">I", zlib.crc32(ctype + body) & 0xFFFFFFFF)
        )

    ihdr = struct.pack(">IIBBBBB", size, size, 8, 2, 0, 0, 0)
    idat = zlib.compress(b"".join(rows), 9)
    png = (
        b"\x89PNG\r\n\x1a\n"
        + chunk(b"IHDR", ihdr)
        + chunk(b"IDAT", idat)
        + chunk(b"IEND", b"")
    )
    with open(os.path.join(OUT_DIR, "diffuse.png"), "wb") as f:
        f.write(png)


if __name__ == "__main__":
    write_obj()
    write_mtl()
    write_png()
    print("wrote knot.obj, knot.mtl, diffuse.png")
