//! Regenerates the sample `solarxy.toml` at the repo root.
//!
//! ```text
//! cargo run -p solarxy-core --example gen_default_config > solarxy.toml
//! ```
//!
//! The example emits header comments explaining each section, then dumps
//! the serialized [`ProjectConfig::default`]. Studios edit the file in
//! place; the canonical defaults always live in `ProjectConfig` itself.

use solarxy_core::project_config::ProjectConfig;

fn main() {
    let cfg = ProjectConfig::default();
    let body = toml::to_string_pretty(&cfg).expect("serialize default config");
    println!("# Solarxy project configuration");
    println!("# Generated by `cargo run -p solarxy-core --example gen_default_config`.");
    println!("# Edit in place — every field has a sensible default, so deleting a key");
    println!("# falls back to the value below.");
    println!("#");
    println!("# Schema reference (enables IDE autocomplete in VS Code, JetBrains, etc.):");
    println!(
        "#:schema https://raw.githubusercontent.com/marko-koljancic/solarxy/main/schemas/solarxy-config.v1.json"
    );
    println!();
    println!("# Solarxy bumps this number when the schema is incompatibly extended.");
    println!("# Newer configs still load on older Solarxy with a warning.");
    println!();
    print!("{body}");
    println!();
    println!("# [[filenames.rules]]");
    println!("# pattern = \"^hero_\"        # any model whose filename starts with hero_");
    println!("# category = \"hero\"          # gets the Hero triangle budget");
    println!();
    println!("# [[filenames.rules]]");
    println!("# pattern = \"^env_\"");
    println!("# category = \"environment\"");
}
